evaluate:
  # No background channel is added for this task. GT 255 pixels are ignored by
  # the MMSeg dataset evaluator instead.
  pamr: false
  bg_thresh: 0.4
  kp_w: 0.0

  pred_qual_path: null
  gt_qual_path: null

  eval_only: true
  template: sub_imagenet_template
  task:
    - partimagenet40

  partimagenet40: src/open_vocabulary_segmentation/segmentation/configs/_base_/datasets/partimagenet40_part.py
